development:
  adapter: redis

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  ssl_params:
    verify_mode: <%= ENV['REDISCLOUD_URL'].nil? ? OpenSSL::SSL::VERIFY_NONE : OpenSSL::SSL::VERIFY_PEER %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # TODO: change bmx4 to the actual app name
  channel_prefix: bmx4_rails_production
  ssl_params:
    verify_mode: <%= ENV['REDISCLOUD_URL'].nil? ? OpenSSL::SSL::VERIFY_NONE : OpenSSL::SSL::VERIFY_PEER %>
