# TODO configure this
default: &default
  application_name: BMX4
  business_name: BMX4 Perfuraçõed
  short_name: BMX4
  domain: https://www.bmx4.com.br/
  support_email: contato@bmx4.com.br
  default_from_email: BMX4 <contato@bmx4.com.br>
  business_address: |-
    Rua Luís Góis, 854 - Mirandópolis, São Paulo - SP, 04043-050
  background_job_processor: sidekiq
  email_provider: postmark

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
